/**
 * Security Audit Script
 * 
 * This script identifies all controllers and checks their security configuration:
 * - Authentication guards (JwtAuthGuard)
 * - Authorization guards (RolesGuard)
 * - Ownership guards (ResourceOwnerGuard)
 * - Public routes
 * 
 * Run with: ts-node src/scripts/security-audit.ts
 */

import * as fs from 'fs';
import * as path from 'path';

interface SecurityIssue {
  file: string;
  endpoint: string;
  issue: string;
  severity: 'critical' | 'high' | 'medium' | 'low';
}

const issues: SecurityIssue[] = [];

/**
 * Controllers that need to be audited
 * This list should be dynamically generated by scanning the modules directory
 */
const CONTROLLERS_TO_AUDIT = [
  'apps/backend/src/modules/auth/auth.controller.ts',
  'apps/backend/src/modules/users/users.controller.ts',
  'apps/backend/src/modules/lms/courses/courses.controller.ts',
  'apps/backend/src/modules/lms/enrollments/enrollments.controller.ts',
  'apps/backend/src/modules/lms/assignments/assignments.controller.ts',
  'apps/backend/src/modules/lms/quizzes/quizzes.controller.ts',
  'apps/backend/src/modules/lms/lessons/lessons.controller.ts',
  'apps/backend/src/modules/lms/instructor/instructor.controller.ts',
  'apps/backend/src/modules/lms/student/student.controller.ts',
  'apps/backend/src/modules/lms/sessions/sessions.controller.ts',
  'apps/backend/src/modules/social/posts/posts.controller.ts',
  'apps/backend/src/modules/social/groups/groups.controller.ts',
  'apps/backend/src/modules/social/pages/pages.controller.ts',
  'apps/backend/src/modules/media/media.controller.ts',
  'apps/backend/src/modules/comments/comments.controller.ts',
  'apps/backend/src/modules/notes/notes.controller.ts',
  'apps/backend/src/modules/events/events.controller.ts',
  'apps/backend/src/modules/jobs/jobs.controller.ts',
  'apps/backend/src/modules/chat/chat.controller.ts',
  'apps/backend/src/modules/notifications/notifications.controller.ts',
  'apps/backend/src/modules/subscriptions/subscriptions.controller.ts',
  'apps/backend/src/modules/plans/plans.controller.ts',
  'apps/backend/src/modules/payments/payments.controller.ts',
  'apps/backend/src/modules/tickets/tickets.controller.ts',
  'apps/backend/src/modules/cms/cms.controller.ts',
  'apps/backend/src/modules/audit/audit.controller.ts',
  'apps/backend/src/modules/ads/ads.controller.ts',
  'apps/backend/src/modules/ads/admin-ads.controller.ts',
  'apps/backend/src/modules/ads/ad-campaigns.controller.ts',
  'apps/backend/src/modules/ads/ads-tracking.controller.ts',
  'apps/backend/src/modules/favorites/favorites.controller.ts',
  'apps/backend/src/modules/shares/shares.controller.ts',
  'apps/backend/src/modules/lookups/lookups.controller.ts',
  'apps/backend/src/modules/lookups/lookup-types.controller.ts',
];

/**
 * Check if a controller file has proper authentication
 */
function checkAuthentication(content: string, file: string): void {
  const hasJwtGuard = content.includes('JwtAuthGuard');
  const hasUseGuards = content.includes('@UseGuards');
  const hasPublicDecorator = content.includes('@Public()');

  if (!hasJwtGuard && !hasPublicDecorator) {
    issues.push({
      file,
      endpoint: 'controller',
      issue: 'No JwtAuthGuard or @Public decorator found - endpoints may be unprotected',
      severity: 'critical',
    });
  }
}

/**
 * Check if a controller has proper authorization
 */
function checkAuthorization(content: string, file: string): void {
  const hasRolesGuard = content.includes('RolesGuard');
  const hasRolesDecorator = content.includes('@Roles(');
  const usesStringRoles = /@Roles\(['"]/.test(content);

  if (!hasRolesGuard && !content.includes('@Public()')) {
    issues.push({
      file,
      endpoint: 'controller',
      issue: 'No RolesGuard found - authorization may not be enforced',
      severity: 'high',
    });
  }

  if (usesStringRoles) {
    issues.push({
      file,
      endpoint: 'controller',
      issue: 'Uses string roles instead of Role enum - should use Role.ADMIN, etc.',
      severity: 'medium',
    });
  }
}

/**
 * Check if a controller has ownership guards where needed
 */
function checkOwnership(content: string, file: string): void {
  const hasResourceOwnerGuard = content.includes('ResourceOwnerGuard');
  const hasResourceTypeDecorator = content.includes('@ResourceType(');
  const hasParamId = content.includes('@Param(\'id\')') || content.includes('@Param("id")');
  const hasUpdateOrDelete = content.includes('@Patch(') || content.includes('@Delete(');

  if (hasParamId && hasUpdateOrDelete && !hasResourceOwnerGuard && !content.includes('@SkipOwnership()')) {
    issues.push({
      file,
      endpoint: 'controller',
      issue: 'Has update/delete endpoints with :id but no ResourceOwnerGuard - users may access others\' data',
      severity: 'critical',
    });
  }

  if (hasResourceOwnerGuard && !hasResourceTypeDecorator) {
    issues.push({
      file,
      endpoint: 'controller',
      issue: 'Has ResourceOwnerGuard but missing @ResourceType decorator',
      severity: 'high',
    });
  }
}

/**
 * Main audit function
 */
async function runAudit(): Promise<void> {
  console.log('🔒 Running Security Audit...\n');

  for (const controllerPath of CONTROLLERS_TO_AUDIT) {
    const fullPath = path.join(process.cwd(), controllerPath);
    
    if (!fs.existsSync(fullPath)) {
      console.log(`⚠️  Controller not found: ${controllerPath}`);
      continue;
    }

    const content = fs.readFileSync(fullPath, 'utf-8');
    
    checkAuthentication(content, controllerPath);
    checkAuthorization(content, controllerPath);
    checkOwnership(content, controllerPath);
  }

  // Print results
  console.log('='.repeat(80));
  console.log('SECURITY AUDIT RESULTS');
  console.log('='.repeat(80));
  console.log();

  if (issues.length === 0) {
    console.log('✅ No security issues found!\n');
    return;
  }

  // Group by severity
  const critical = issues.filter(i => i.severity === 'critical');
  const high = issues.filter(i => i.severity === 'high');
  const medium = issues.filter(i => i.severity === 'medium');
  const low = issues.filter(i => i.severity === 'low');

  console.log(`Total Issues: ${issues.length}\n`);
  console.log(`🔴 Critical: ${critical.length}`);
  console.log(`🟠 High: ${high.length}`);
  console.log(`🟡 Medium: ${medium.length}`);
  console.log(`🟢 Low: ${low.length}`);
  console.log();

  // Print critical issues first
  if (critical.length > 0) {
    console.log('🔴 CRITICAL ISSUES:');
    console.log('-'.repeat(80));
    critical.forEach((issue, index) => {
      console.log(`${index + 1}. ${issue.file}`);
      console.log(`   Issue: ${issue.issue}`);
      console.log();
    });
  }

  if (high.length > 0) {
    console.log('🟠 HIGH PRIORITY ISSUES:');
    console.log('-'.repeat(80));
    high.forEach((issue, index) => {
      console.log(`${index + 1}. ${issue.file}`);
      console.log(`   Issue: ${issue.issue}`);
      console.log();
    });
  }

  if (medium.length > 0) {
    console.log('🟡 MEDIUM PRIORITY ISSUES:');
    console.log('-'.repeat(80));
    medium.forEach((issue, index) => {
      console.log(`${index + 1}. ${issue.file}`);
      console.log(`   Issue: ${issue.issue}`);
      console.log();
    });
  }

  console.log('='.repeat(80));
  console.log('\n📋 Action Required: Fix all critical and high priority issues before deployment.\n');
}

// Run the audit
runAudit().catch(console.error);
