// LMS Email Templates
export * from './course-enrollment.template';
export * from './course-enrollment-approved.template';
export * from './assignment-graded.template';
export * from './certificate-issued.template';
export * from './lesson-unlocked.template';
export * from './assignment-assigned.template';
export * from './assignment-submitted.template';
export * from './assignment-due-soon.template';
export * from './quiz-graded.template';
export * from './instructor-message.template';
export * from './course-updated.template';
