import { Injectable, Inject, Logger } from '@nestjs/common';
import { NodePgDatabase } from 'drizzle-orm/node-postgres';
import { eq, and } from 'drizzle-orm';
import { paymentHistory, users } from '@leap-lms/database';
import PDFDocument from 'pdfkit';
import { join } from 'path';
import { existsSync, mkdirSync } from 'fs';

@Injectable()
export class PdfService {
  private readonly logger = new Logger(PdfService.name);
  private readonly invoicesDir = join(process.cwd(), 'storage', 'invoices');

  constructor(
    @Inject('DRIZZLE_DB') private readonly db: NodePgDatabase<any>,
  ) {
    // Ensure directory exists
    if (!existsSync(this.invoicesDir)) {
      mkdirSync(this.invoicesDir, { recursive: true });
    }
  }

  async generateInvoicePDF(paymentId: number): Promise<{ filePath: string; downloadUrl: string }> {
    const payment = await this.db
      .select()
      .from(paymentHistory)
      .where(and(eq(paymentHistory.id, paymentId), eq(paymentHistory.isDeleted, false)))
      .limit(1);

    if (!payment || payment.length === 0) {
      throw new Error(`Payment with ID ${paymentId} not found`);
    }

    const paymentData = payment[0];
    
    // Get user information
    const [user] = await this.db
      .select()
      .from(users)
      .where(eq(users.id, paymentData.userId))
      .limit(1);

    const invoiceNumber = paymentData.invoiceNumber || `INV-${paymentId}`;
    const fileName = `${invoiceNumber}.pdf`;
    const filePath = join(this.invoicesDir, fileName);

    // Generate PDF
    const doc = new PDFDocument({ margin: 50 });
    const stream = require('fs').createWriteStream(filePath);
    doc.pipe(stream);

    // Header
    doc.fontSize(20).text('INVOICE', { align: 'center' });
    doc.moveDown();

    // Invoice details
    doc.fontSize(12);
    doc.text(`Invoice Number: ${invoiceNumber}`, { align: 'left' });
    doc.text(`Date: ${paymentData.paymentDate ? new Date(paymentData.paymentDate).toLocaleDateString() : new Date().toLocaleDateString()}`, { align: 'left' });
    doc.moveDown();

    // Bill To
    if (user) {
      doc.text('Bill To:', { underline: true });
      doc.text(user.firstName && user.lastName ? `${user.firstName} ${user.lastName}` : user.email || 'N/A');
      if (user.email) doc.text(user.email);
      doc.moveDown();
    }

    // Payment details
    doc.text('Payment Details:', { underline: true });
    doc.text(`Transaction ID: ${paymentData.transactionId || 'N/A'}`);
    doc.text(`Amount: ${paymentData.currency || 'USD'} ${paymentData.amount || '0.00'}`);
    doc.text(`Payment Method: ${paymentData.paymentMethod || 'N/A'}`);
    doc.text(`Status: ${paymentData.status || 'N/A'}`);
    doc.moveDown();

    // Footer
    doc.fontSize(10)
      .text('Thank you for your business!', { align: 'center' })
      .moveDown()
      .text('This is an automated invoice generated by LEAP PM', { align: 'center' });

    doc.end();

    return new Promise((resolve, reject) => {
      stream.on('finish', async () => {
        try {
          // Use API endpoint for download
          const downloadUrl = `/api/payments/${paymentId}/invoice/download`;
          resolve({ filePath, downloadUrl });
        } catch (error) {
          reject(error);
        }
      });

      stream.on('error', reject);
    });
  }

  async getInvoicePDFPath(paymentId: number): Promise<string | null> {
    const payment = await this.db
      .select()
      .from(paymentHistory)
      .where(and(eq(paymentHistory.id, paymentId), eq(paymentHistory.isDeleted, false)))
      .limit(1);

    if (!payment || payment.length === 0) {
      return null;
    }

    const invoiceNumber = payment[0].invoiceNumber || `INV-${paymentId}`;
    const fileName = `${invoiceNumber}.pdf`;
    const filePath = join(this.invoicesDir, fileName);

    if (existsSync(filePath)) {
      return filePath;
    }

    return null;
  }
}
